version = 3

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Icon }} '
    foreground = '#26C6DA'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    template = '   {{ .Name }} '
    foreground = '#FFE700'
    type = 'shell'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = '#26C6DA'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = '➜ ({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Major }}.{{ .Minor }}{{ end }}) '
    foreground = '#0fc469'
    type = 'python'
    style = 'powerline'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#FFE700'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}', '{{ if gt .Ahead 0 }}#16c60c{{ end }}', '{{ if gt .Behind 0 }}#f450de{{ end }}']

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }} '
    foreground = '#ffffff'
    background = '#6CA35E'
    type = 'node'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = ' {{ .Full }} '
    foreground = '#ffffff'
    background = '#4c1f5e'
    type = 'java'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ if gt .Code 0 }}<#ff0000></>{{ else }}<#23d18b></>{{ end }} '
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    template = 'took  {{ .FormattedMs }} '
    foreground = '#bab02a'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 10.0

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }}  '
    foreground = '#00C5C7'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#77E4F7'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = '❯ '
    foreground = '#43D426'
    type = 'text'
    style = 'plain'
